blog/urls.py
from django.urls import path, include

from blog.views.api.comment import comment
from blog.views.api.like import post_like
from blog.views.blog import PostList, PostDetail, PostFeed

urlpatterns = [
    path(
        'api/posts/<int:post_pk>/',
        include(
            [
                path('comment/', comment, name='api-post-comment'),
                path('like/', post_like, name='api-post-like'),
            ]
        ),
    ),
    path('', PostList.as_view(), name='post-list'),
    path('<slug:slug>/', PostDetail.as_view(), name='post-detail'),
    path('latest/feed/', PostFeed(), name='post-feed'),
]

studio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework import routers

import blender_id_oauth_client.urls

import blog.urls
import comments.urls
import projects.urls
import search.urls
import looper.urls
import subscriptions.urls
import training.urls
import static_assets.urls
import users.urls
import characters.urls

from common.views.api.markdown_preview import markdown_preview as markdown_preview_view
from common.views.home import home as home_view, welcome as welcome_view
import common.views.errors as error_views
import static_assets.viewsets
import training.viewsets
from projects.views.project import film_list

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.enable_nav_sidebar = False

router = routers.DefaultRouter(trailing_slash=True)
router.register(r'static-asset', static_assets.viewsets.StaticAssetViewSet)
router.register(r'training/section', training.viewsets.SectionViewSet)
# To leverage the docs boilerplate, a view set is used for single endpoint here too.
router.register(r'upload', static_assets.viewsets.UploadViewSet, basename='upload')
router.get_api_root_view().cls.__name__ = "API"
router.get_api_root_view().cls.__doc__ = "Blender Studio API"


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('', home_view, name='home'),
    path('welcome/', welcome_view, name='welcome'),
    path('comments/', include(comments.urls)),
    path('films/', film_list, name='film-list'),
    path('projects/', include(projects.urls)),
    path('training/', include(training.urls)),
    path('blog/', include(blog.urls)),
    path('api/markdown-preview', markdown_preview_view, name='api-markdown-preview'),
    path('api/', include((router.urls, 'api'), namespace='api')),
    path('', include(characters.urls)),
    path('search/', include(search.urls)),
    path('looper/', include((looper.urls), namespace='looper')),
    path('', include((subscriptions.urls), namespace='subscriptions')),
    path('', include(users.urls)),
    path('', include(static_assets.urls)),
    path('stats/', include('stats.urls')),
    path('activity/', include('actstream.urls')),
    re_path(r'^webhooks/', include('anymail.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('s3direct/', include('s3direct.urls')),
]

handler400 = error_views.ErrorView.as_view(template_name='common/errors/400.html', status=400)
handler403 = error_views.ErrorView.as_view(template_name='common/errors/403.html', status=403)
handler404 = error_views.ErrorView.as_view(template_name='common/errors/404.html', status=404)
handler500 = error_views.ErrorView.as_view(template_name='common/errors/500.html', status=500)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Test different error pages by changing the template (400.html, 403.html, etc.)
    urlpatterns += [path('error', TemplateView.as_view(template_name='common/errors/404.html'))]

    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

# Flatpages catch-all
urlpatterns += [
    re_path(r'^(?P<url>.*/)$', views.flatpage),
]

subscriptions/urls.py
from django.urls import path, re_path

from looper.views import settings as looper_settings
from looper.views import checkout_stripe

from subscriptions.views.join import JoinView
from subscriptions.views.select_plan_variation import (
    SelectPlanVariationView,
    SelectTeamPlanVariationView,
)
from subscriptions.views.teams import TeamsLanding
import subscriptions.views.settings as settings
import subscriptions.views.webhooks as webhooks

# Required for URL namespace to work
app_name = 'subscriptions'

urlpatterns = [
    re_path(
        r'^join/(?:plan-variation/(?P<plan_variation_id>\d+)/)?$',
        SelectPlanVariationView.as_view(),
        name='join',
    ),
    re_path(
        r'^join/team/(?:plan-variation/(?P<plan_variation_id>\d+)/)?$',
        SelectTeamPlanVariationView.as_view(),
        name='join-team',
    ),
    path(
        'join/plan-variation/<int:plan_variation_id>/billing/',
        JoinView.as_view(),
        name='join-billing-details',
    ),
    path(
        'join/plan-variation/<int:plan_variation_id>/done/<str:stripe_session_id>/',
        checkout_stripe.StripeSuccessCreateSubscriptionView.as_view(),
        name='join-done',
    ),
    path(
        'subscription/<int:subscription_id>/manage/',
        settings.ManageSubscriptionView.as_view(),
        name='manage',
    ),
    path(
        'subscription/<int:subscription_id>/cancel/',
        settings.CancelSubscriptionView.as_view(),
        name='cancel',
    ),
    path(
        'subscription/<int:subscription_id>/payment-method/change/',
        settings.PaymentMethodChangeView.as_view(),
        name='payment-method-change',
    ),
    path(
        'subscription/<int:subscription_id>/payment-method/change/<stripe_session_id>/',
        settings.PaymentMethodChangeDoneView.as_view(),
        name='payment-method-change-done',
    ),
    path('webhooks/stripe/', webhooks.StripeWebhookView.as_view()),
    path(
        'subscription/order/<int:order_id>/pay/',
        settings.PayExistingOrderView.as_view(),
        name='pay-existing-order',
    ),
    path(
        'settings/billing-address/', settings.BillingAddressView.as_view(), name='billing-address'
    ),
    path('settings/receipts/', looper_settings.settings_receipts, name='receipts'),
    path(
        'settings/receipts/<int:order_id>',
        looper_settings.ReceiptView.as_view(),
        name='receipt',
    ),
    path(
        'settings/receipts/blender-studio-<int:order_id>.pdf',
        looper_settings.ReceiptPDFView.as_view(),
        name='receipt-pdf',
    ),
    path('teams/', TeamsLanding.as_view(), name='teams-landing'),
]

common/models.py
from django.db import models

from common import mixins
from common import validators


class TemplateVariable(mixins.CreatedUpdatedMixin, models.Model):
    """Store text and/or images to be used in templates.

    Currently, only front page '/' and '/welcome/' load these into their
    template contexts.
    N.B.: it's up to the templates to access and handles these correctly.
    """

    key = models.CharField(
        blank=False,
        help_text="Name of the variable, use this to access the variable in the template context.",
        max_length=30,
        null=False,
        unique=True,
        validators=[validators.validate_variable_key],
    )
    text = models.TextField(
        blank=True,
        default='',
        help_text=(
            'Text value of the variable.'
            ' Use "{{ key.text }}" to refer to this value in a template.'
        ),
        max_length=500,
        null=False,
    )
    image = models.ImageField(
        null=True,
        blank=True,
        help_text=(
            'Image value of the variable.'
            ' Use "{{ key.url }}" to access URL of this image in a template.'
        ),
    )

    class Meta:
        ordering = ['key']

    def __str__(self) -> str:
        return f'TemplateVariable "{self.key}"'

    def __bool__(self):
        return bool(self.image) or bool(self.text)

    def url(self) -> str:
        return self.image.url if self.image else ''

comments/views/common.py
# noqa: D100
from typing import Dict, List, Optional, Sequence
import json

from django.contrib.auth import get_user_model
from django.db import transaction
from django.http import JsonResponse

from comments import typed_templates
from comments.models import Comment
from common import markdown
from common.types import assert_cast

User = get_user_model()


def comments_to_template_type(
    comments: Sequence[Comment], comment_url: str, user: User
) -> typed_templates.Comments:
    # noqa: D103
    user_is_moderator = user.has_perm('comments.moderate_comment')
    lookup: Dict[Optional[int], List[Comment]] = {}
    # Sort all comments chronologically, oldest first
    for comment in sorted(comments, key=lambda c: c.date_created):
        reply_to_pk = None if comment.reply_to is None else comment.reply_to.pk

        lookup.setdefault(reply_to_pk, []).append(comment)

    def build_tree(comment: Comment) -> typed_templates.CommentTree:
        if comment.is_deleted:
            return build_deleted_tree(comment)
        # FIXME(anna) remove when all comments have message_html
        comment.message_html = comment.message_html or markdown.render(
            markdown.sanitize(comment.message)
        )
        return typed_templates.CommentTree(
            id=comment.pk,
            anchor=comment.anchor,
            full_name=comment.full_name or comment.username,
            date=comment.date_created,
            message=assert_cast(str, comment.message),
            message_html=assert_cast(str, comment.message_html),
            like_url=comment.like_url,
            liked=assert_cast(bool, getattr(comment, 'liked')),
            likes=assert_cast(int, getattr(comment, 'number_of_likes')),
            replies=[build_tree(reply) for reply in lookup.get(comment.pk, [])],
            profile_image_url=comment.profile_image_url,
            badges=comment.badges,
            edit_url=(
                comment.edit_url
                if assert_cast(bool, getattr(comment, 'owned_by_current_user'))
                else None
            ),
            admin_edit_url=comment.edit_url if user_is_moderator else None,
            archive_tree_url=comment.archive_tree_url if user_is_moderator else None,
            delete_url=(
                comment.delete_url
                if assert_cast(bool, getattr(comment, 'owned_by_current_user'))
                else None
            ),
            admin_delete_url=comment.delete_url if user_is_moderator else None,
            delete_tree_url=comment.delete_tree_url if user_is_moderator else None,
            hard_delete_tree_url=comment.hard_delete_tree_url if user_is_moderator else None,
            edited=(comment.date_updated != comment.date_created),
            is_archived=comment.is_archived,
            is_top_level=True if comment.reply_to is None else False,
        )

    def build_deleted_tree(comment: Comment) -> typed_templates.DeletedCommentTree:
        """
        Prepare comments marked as deleted to be displayed in the comment tree.

        Deleted comments with replies have to be kept in the database to preserve
        the integrity of the conversation, but their message and user should not
        be displayed. It should also be impossible to edit or delete them again.
        """
        return typed_templates.DeletedCommentTree(
            id=comment.pk,
            anchor=comment.anchor,
            date=comment.date_created,
            replies=[build_tree(reply) for reply in lookup.get(comment.pk, [])],
            is_archived=comment.is_archived,
            is_top_level=True if comment.reply_to is None else False,
        )

    # Top-level comments are ordered by number of likes and date
    top_level_comments = sorted(
        (comment for comment in lookup.get(None, [])),
        key=lambda c: (-c.number_of_likes, c.date_created),
    )

    return typed_templates.Comments(
        comment_url=comment_url,
        number_of_comments=len(comments),
        comment_trees=[build_tree(comment) for comment in top_level_comments],
        profile_image_url=user.image_url if getattr(user, 'image', None) else None,
    )


def comment_response(request, comment_model, to_field, field_pk):
    """Add a comment linked to a specific model and pk."""
    parsed_body = json.loads(request.body)

    reply_to_pk = int(parsed_body['reply_to']) if parsed_body.get('reply_to') else None
    message = assert_cast(str, parsed_body['message'])

    @transaction.atomic
    def create_comment(
        *, user_pk: int, message: str, reply_to_pk: Optional[int], **kwargs
    ) -> Comment:
        comment = Comment.objects.create(user_id=user_pk, message=message, reply_to_id=reply_to_pk)
        comment_model.objects.create(comment_id=comment.id, **kwargs)
        return comment

    m2m_params = {to_field: field_pk}
    comment = create_comment(
        user_pk=request.user.pk, message=message, reply_to_pk=reply_to_pk, **m2m_params
    )

    return JsonResponse(comment.to_dict())

common/views/errors.py
"""Error handlers."""

from django.http import HttpResponse
from django.views.generic import TemplateView


class ErrorView(TemplateView):
    """Renders an error page."""

    # TODO: respond as JSON when this is an XHR.

    status = 500

    def dispatch(self, request=None, *args, **kwargs):
        if request is None or request.method in {'HEAD', 'OPTIONS'}:
            # Don't render templates in this case.
            return HttpResponse(status=self.status)

        # We allow any method for this view,
        response = self.render_to_response(self.get_context_data(**kwargs))
        response.status_code = self.status
        return response


def csrf_failure(request, reason=""):
    import django.views.csrf

    return django.views.csrf.csrf_failure(
        request, reason=reason, template_name='errors/403_csrf.pug'
    )

common/views/home.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_safe

import blog.models as models_blog
from common.models import TemplateVariable
from common.queries import get_latest_trainings_and_production_lessons
from projects.models import Project
from projects.queries import (get_production_logs, get_random_featured_assets)
from training.models import Training, Section
from training.queries.sections import recently_watched
from training.views.common import recently_watched_sections_to_template


@require_safe
def home(request: HttpRequest) -> HttpResponse:
    """
    Render the home page of Blender Studio.

    **Context**:
        ``records``
            A paginator Page object with dictionaries representing recently created objects:
            instances of :model:`blog.Post`, :model:`ProductionLog`, or
            :model:`training.Training`. The dictionaries have the following keys:

            - 'pk': int - the primary key of the related object,
            - 'date_created': datetime - the date when the object was created,
            - 'obj_type': str - specifies the type (model) of the object,
            - 'object': a particular Model instance.

    **Template**
        :template:`common/home.html`
    """
    if not request.user.is_authenticated:
        return redirect('welcome')

    context = {
        'featured_projects': Project.objects.filter(is_featured=True),
        'featured_trainings': get_latest_trainings_and_production_lessons(),
        'featured_project_assets': get_random_featured_assets(limit=8),
        'latest_posts': models_blog.Post.objects.filter(is_published=True)[:6],
        'recently_watched_sections': [],
        **{entry.key: entry for entry in TemplateVariable.objects.all()},
    }

    try:
        frontpage_project_slug = TemplateVariable.objects.get(
            key='frontpage_project_slug'
        )
        frontpage_project = Project.objects.get(slug=frontpage_project_slug.text)
        frontpage_project_production_logs = get_production_logs(frontpage_project)
        context['frontpage_project_production_logs'] = frontpage_project_production_logs
    except (Project.DoesNotExist, TemplateVariable.DoesNotExist):
        context['frontpage_project_production_logs'] = None

    if request.user.is_authenticated:
        recently_watched_sections = recently_watched(user_pk=request.user.pk)
        context['recently_watched_sections'] = recently_watched_sections_to_template(
            recently_watched_sections
        )

    return render(request, 'common/home.html', context)


@require_safe
def welcome(request: HttpRequest) -> HttpResponse:
    """
    Render the welcome page of Blender Studio.

    **Context**:
        ``featured_projects``
            A queryset of projects marked as featured.
        ``featured_trainings``
            A queryset of trainings marked as featured.

    **Template**
        :template:`common/welcome.html`
    """
    context = {
        'featured_projects': Project.objects.filter(is_featured=True),
        'featured_trainings': Training.objects.filter(is_featured=True),
        'featured_sections': Section.objects.filter(is_featured=True, is_published=True),
        'featured_project_assets': get_random_featured_assets(limit=8),
        'next_home': True,
        **{entry.key: entry for entry in TemplateVariable.objects.all()},
    }

    return render(request, 'common/welcome.html', context)

common/templates/common/components/alert_coupon_announcement.html
{% if coupon_announcement %}
  <div class="container my-3 text-center">
    <a href="{% url 'user-settings' %}" class="alert alert-warning show" role="alert">
      {{ coupon_announcement.text | safe }}
    </a>
  </div>
{% endif %}

common/templates/common/components/content_locked.html
{% load static %}

<div class="align-items-center content-locked d-flex overflow-hidden position-relative rounded w-100">
  {% if show_background %}
  <img class="content-locked-img img-fluid w-100" src="{% if background %}{{ background }}{% else %}{% static 'training/images/placeholders/card.jpg' %}{% endif %}">
  <div class="bg-overlay"></div>
  {% endif %}
  <div class="{% if show_background %}position-absolute{% else %}py-5{% endif %} row text-center w-100">
    <div class="col-12">
      <h3>
        {{ request.user.is_authenticated|yesno:"Subscribe,Login" }} to view this content
      </h3>
      <p class="mb-4 mx-auto" style="max-width: 700px; text-wrap: balance;">
        Join Blender Studio for just €11.50/month and get instant access to all of our training and film assets!
      </p>
      <div class="btn-row justify-content-center">
        {% if not request.user.is_authenticated %}
          <a href="{% url 'oauth:login' %}" class="btn btn-link text-white">Login</a>
        {% endif %}
          <a href="{% url 'subscriptions:join' %}" class="btn btn-accent px-5 text-white">Join Blender Studio</a>
        </div>
    </div>
  </div>
</div>

common/templates/common/components/faq.html
<section class="{{ classes }}">
  <div class="mb-5 row">
    <div class="col-md-4">
      <h1>Frequently asked <span class="text-muted">questions.</span></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <h3>General</h3>
      <details>
        <summary>What is Blender Studio?</summary>
        <p>
          Blender Studio is a Film and Training publishing platform for everything produced by the Studio team.
        </p>
      </details>
      <details>
        <summary>How is my money spent?</summary>
        <p>
          The money Blender Studio makes through subscriptions is used to keep our services running, and to make
          open source and open content productions possible. Throughout the production cycle our team produce
          training, rigs and assets for publishing to Blender Studio subscribers.
        </p>
      </details>

      <details>
        <summary>How does Blender Studio support Blender?</summary>
        <p>
          The Blender Studio website funds the Blender Studio team, who rigorously tests and use Blender in the Open Movie
          productions. The team works with core Blender developers at the Blender Institute to plan, design and
          test core Blender features.
        </p>
      </details>
    </div>
    <div class="col-6">
      <h3>Payment & Billing</h3>
      <details>
        <summary>What payment methods do you accept?</summary>
        <p>
          Blender Studio offers payment through major credit cards, PayPal or direct bank transfer.
        </p>
      </details>

      <details>
        <summary>How easy is it to cancel my subscription?</summary>
        <p>
          In case of suspected fraud or abuse of the service after registration and membership payment, the
          account owner will be contacted and asked for clarification. Failure to alleviate charges of fraud may
          result in the termination of the member’s account.<br>
          <br>
          Upon termination, all licenses granted by the Blender Studio will terminate. In the event of account
          deletion for any reason, content that you submitted may no longer be available. The Blender Studio shall
          not be responsible for the loss of such content.
        </p>
      </details>
      <details>
        <summary>Can I get a refund?</summary>
        <p>
          Membership fees and supporter contributions are non-refundable. That money keeps our services running,
          and is used to make open source and open content productions possible.<br>
          <br>
          We really care about our members and supporters though — in case you are really not happy with
          our Blender Studio we will kindly respond to your comments and try to settle a dispute with you in
          harmony.<br>
          <br>
          Refunds will happen without delay when we get a report of fraud, abuse or non-authorised usage of
          funds.<br>
          <br>
          Contact: <a href="mailto:{{ ADMIN_MAIL }}">{{ ADMIN_MAIL }}</a>.
        </p>
      </details>
    </div>
  </div>
</section>

common/templates/common/components/file.html
{% load static %}
{% load thumbnail %}
{% load common_extras %}

{# Classes 'file-*' and 'grid-*' are used by js #}
<div class="cards-item-file cards-item file grid-item overflow-hidden {{ card_sizes|default:'col-12 col-sm-6 col-md-6 col-lg-4' }} {% if aspect_ratio == '16:9' %}widescreen{% elif aspect_ratio == '4:3' %}fourbythree{% elif aspect_ratio == '1:1' %}square{% endif %} {% if asset.is_spoiler or not user_can_view_asset and not asset.is_free  %}locked{% endif %}">
  <a class="cards-item-content file-modal-link" data-asset-id="{{ asset.id }}" data-url="{% url 'api-asset' asset.id %}?site_context={{ site_context }}">
    <div class="cards-item-thumbnail">
      {% if asset.static_asset.thumbnail %}
        {% if user_can_view_asset or asset.is_free %}
          {% if asset.is_spoiler %}
            {% include "common/components/helpers/image_resize.html" with alt=asset.name classes="file-img" img_source=asset.static_asset.thumbnail width="200" %}
          {% else %}
            {% if image_size %}
              {% include "common/components/helpers/image_resize.html" with alt=asset.name classes="file-img" img_source=asset.static_asset.thumbnail width=image_size %}
            {% else %}
              {% include "common/components/helpers/image_resize.html" with alt=asset.name classes="file-img" img_source=asset.static_asset.thumbnail width="350" %}
            {% endif %}
          {% endif %}
        {% else %}
          {% include "common/components/helpers/image_resize.html" with alt=asset.name classes="file-img" img_source=asset.static_asset.thumbnail width="200" %}
        {% endif %}

        {% if user_can_view_asset or asset.is_free %}
          {% if asset.is_spoiler %}
            {# Spoiler alert #}
            <div class="file-lock-text overflow-hidden rounded-lg">
              <h4 class="mb-0"><i class="i-alert-triangle"></i> Spoiler</h4>
            </div>
          {% endif %}
        {% else %}
          <div class="file-lock-text overflow-hidden rounded-lg">
            <p class="mb-0">
              <i class="i-lock"></i> Subscribe to view
            </p>
          </div>
        {% endif %}
      {% else %}
        <div class="cards-item-thumbnail-icon"><i class="i-mediatype-{{ asset.static_asset.source_type }}"></i></div>
      {% endif %}

      {% if asset.contains_blend_file %}
        <div class="cards-item-thumbnail-icon-overlay"><i class="i-blender"></i></div>
      {% elif asset.static_asset.source_type == "file" %}
        <div class="cards-item-thumbnail-icon-overlay"><i class="i-file"></i></div>
      {% elif asset.static_asset.source_type == "video" %}
        <div class="cards-item-thumbnail-icon-overlay">
          <div class="badge badge-video-duration m-1">
            {{ asset.static_asset.video.duration_label }}
          </div>
        </div>
      {% endif %}
    </div>

    <div class="position-relative">
      <div class="cards-item-title-overlay position-absolute w-100"></div>
      <h4 class="cards-item-title d-flex mb-0 position-absolute w-100">
        <span data-bs-tooltip="tooltip-overflow" data-placement="top" title="{{ asset.name }}">
          <span class="overflow-text">{{ asset.name }}</span>
        </span>
      </h4>
    </div>
  </a>
</div>

common/templates/common/components/file_carousel.html
{% load static %}
{% load thumbnail %}
{# Class 'card-grid-item' is needed for js #}
<div class="card-grid-item cards-item {{ card_sizes|default:"col-12 col-sm-6 col-lg-3" }}">
  <a aria-label="{{ project_asset.name }}" class="bg-transparent cards-item-content file" href="{{ project_asset.url }}" data-asset-id="{{ project_asset.id }}" data-bs-tooltip="tooltip-overflow" data-placement="top" data-url="{% url 'api-asset' project_asset.id %}?site_context={{ site_context }}" title="{{ asset.name }}">
    <div class="position-relative">
      <div class="cards-item-thumbnail">
        {% if project_asset.static_asset.thumbnail_s_url %}
          <img class="file-img" src="{{ project_asset.static_asset.thumbnail_s_url }}" alt="{{ project_asset.name }}"/>
        {% endif %}
        {% if asset.contains_blend_file %}
          <img class="file-icon" src="{% static "common/images/icons/blend.svg" %}" alt="{{ project_asset.name }}">
        {% elif asset.static_asset.source_type == "file" %}
          <img class="file-icon" src="{% static "common/images/icons/file.svg" %}" alt="{{ project_asset.name }}">
        {% endif %}
        {% if user_can_edit_asset %}
          <a href="{{ asset.admin_url }}" target="_blank" class="btn btn-link">
            <i class="i-edit"></i>
          </a>
        {% endif %}
      </div>
      {% if asset.static_asset.source_type == "video" %}
        <div class="badge badge-video-duration">
          {{ asset.static_asset.video.duration_label }} 1:00
        </div>
      {% endif %}
    </div>
    <h3 class="cards-item-title fs-4 lh-sm oveflow-text">{{ project_asset.name }}</h3>
  </a>
</div>

common/templates/common/components/folder.html
{% load static %}
{% load thumbnail %}
{% load common_extras %}

<div class="cards-item cards-item-file file grid-item {{ card_sizes|default:"col-12 col-sm-6 col-md-6 col-lg-4" }} {% if aspect_ratio == "16:9" %}widescreen{% elif aspect_ratio == "4:3" %}fourbythree{% elif aspect_ratio == "1:1" %}square{% endif %}">
  <a class="cards-item-content" href="{{ child_collection.url }}">
    <div class="position-relative">
      <div class="cards-item-thumbnail {% if not child_collection.thumbnail %}bg-tertiary ratio-16x9{% endif %}">
        {% if child_collection.thumbnail %}
          <img alt="Collection preview" src="{{ child_collection.thumbnail.url }}">
        {% else %}
          <div class="align-items-center position-absolute d-flex justify-content-center">
            <img class="file-icon-img" src="{% static "common/images/icons/folder-grey.svg" %}" alt="Collection preview">
          </div>
        {% endif %}
      </div>
      {% if child_collection.thumbnail %}
        <img class="file-icon" src="{% static "common/images/icons/folder.svg" %}" alt="Folder Icon">
      {% endif %}
    </div>
    <div class="position-relative">
      <div class="cards-item-title-overlay position-absolute w-100"></div>
      <h4 class="cards-item-title d-flex mb-0 position-absolute w-100">
        <span data-bs-tooltip="tooltip-overflow" data-placement="top" title="{{ child_collection.name }}">
          <span class="overflow-text">{{ child_collection.name }}</span>
        </span>
      </h4>
    </div>
  </a>
</div>

common/templates/common/components/meta.html
{% spaceless %}
  {% load static %}
  {% load common_extras %}

  {% with default_title="Blender Studio" %}
    {% with default_author="Blender Studio" %}

      {% with default_description="Blender Studio is a web service that provides access the training videos and all the data from the Blender open projects." %}

        {% if not image_url %}
          {% static 'common/images/blender-studio-og.jpg' as default_image_path %}
          {% absolute_url default_image_path as image_url %}
        {% endif %}

        {% if url %}{% absolute_url url as url %}{% endif %}

        <link rel="canonical" href="{% firstof url canonical_url %}" />
        <meta property="og:url" content="{% firstof url canonical_url %}">

        <meta name="author" content="{% firstof author default_author %}">
        <meta name="theme-color" content="#009eff">
        <meta property="og:site_name" content="Blender Studio">
        <meta property="og:locale" content="en_US">
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@BlenderStudio_">
        <meta property="og:type" content="website">

        <meta property="og:title" content="{% if title %}{{ title }} - {% endif %}{{ default_title }}">
        <meta name="twitter:title" content="{% if title %}{{ title }} - {% endif %}{{ default_title }}">

        <meta name="description" content="{% firstof description default_description %}">
        <meta property="og:description" content="{% firstof description default_description %}">
        <meta name="twitter:description" content="{% firstof description default_description %}">

        <meta property="og:image" content="{{ image_url }}">
        <meta name="twitter:image" content="{{ image_url }}">

      {% endwith %}
    {% endwith %}
  {% endwith %}
{% endspaceless %}

common/templates/common/components/published_by.html
{# TODO: cleanup check if template is needed or referenced #}
{% if static_asset.author %}
  <p class="subtitle text-white-50 x-sm">Author</p>
  <h4 class="comment-name mb-0">{{ static_asset.author.full_name }}</h4>
{% elif static_asset.user.full_name %}
  <p class="subtitle text-white-50 x-sm">Published by</p>
  <h4 class="comment-name mb-0">{{ static_asset.user.full_name }}</h4>
{% elif fallback_user %}
  <p class="subtitle text-white-50 x-sm">Published by</p>
  <h4 class="comment-name mb-0">{{ fallback_user.full_name }}</h4>
{% endif %}

common/templates/common/components/simple_header.html
<div class="justify-content-center mb-3 row">
  <div class="col-md-6 text-center">
    <h1 class="mb-0">{{ title }}</h1>
    <p class="mb-0">{{ subtitle }}</p>
  </div>
</div>