blog/urls.py
from django.urls import path, include

from blog.views.api.comment import comment
from blog.views.api.like import post_like
from blog.views.blog import PostList, PostDetail, PostFeed

urlpatterns = [
    path(
        'api/posts/<int:post_pk>/',
        include(
            [
                path('comment/', comment, name='api-post-comment'),
                path('like/', post_like, name='api-post-like'),
            ]
        ),
    ),
    path('', PostList.as_view(), name='post-list'),
    path('<slug:slug>/', PostDetail.as_view(), name='post-detail'),
    path('latest/feed/', PostFeed(), name='post-feed'),
]

projects/urls.py
from django.urls import path, include

from projects.views import project, gallery, production_log
from projects.views.api.asset import asset as api_asset, asset_zoom, asset_like
from projects.views.api.comment import comment

urlpatterns = [
    path(
        'api/assets/<int:asset_pk>/',
        include(
            [
                path('', api_asset, name='api-asset'),
                path('zoom/', asset_zoom, name='api-asset-zoom'),
                path('comment/', comment, name='api-asset-comment'),
                path('like/', asset_like, name='api-asset-like'),
            ]
        ),
    ),
    path('', project.project_list, name='project-list'),
    path('<slug:project_slug>/', project.project_detail, name='project-detail'),
    path('<slug:project_slug>/gallery/', gallery.collection_list, name='project-gallery'),
    path(
        '<slug:project_slug>/production-credit/',
        project.FilmProductionCreditView.as_view(),
        name='production-credit',
    ),
    path(
        '<slug:project_slug>/production-logs/',
        production_log.ProductionLogPaginatedView.as_view(),
        name='production-logs',
    ),
    path(
        '<slug:project_slug>/production-logs/<int:year>/<str:month>/',
        production_log.ProductionLogMonthView.as_view(),
        name='production-logs-month',
    ),
    path(
        '<slug:project_slug>/production-log/<int:pk>/',
        production_log.ProductionLogDetailView.as_view(),
        name='production-log',
    ),
    path(
        '<slug:project_slug>/all-artwork/', gallery.AllAssets.as_view(), name='project-all-assets'
    ),
    path('<slug:project_slug>/pages/<slug:page_slug>/', project.flatpage, name='project-flatpage'),
    path(
        '<slug:project_slug>/<slug:collection_slug>/',
        gallery.collection_detail,
        name='collection-detail',
    ),
]

studio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework import routers

import blender_id_oauth_client.urls

import blog.urls
import comments.urls
import projects.urls
import search.urls
import looper.urls
import subscriptions.urls
import training.urls
import static_assets.urls
import users.urls
import characters.urls

from common.views.api.markdown_preview import markdown_preview as markdown_preview_view
from common.views.home import home as home_view, welcome as welcome_view
import common.views.errors as error_views
import static_assets.viewsets
import training.viewsets
from projects.views.project import film_list

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.enable_nav_sidebar = False

router = routers.DefaultRouter(trailing_slash=True)
router.register(r'static-asset', static_assets.viewsets.StaticAssetViewSet)
router.register(r'training/section', training.viewsets.SectionViewSet)
# To leverage the docs boilerplate, a view set is used for single endpoint here too.
router.register(r'upload', static_assets.viewsets.UploadViewSet, basename='upload')
router.get_api_root_view().cls.__name__ = "API"
router.get_api_root_view().cls.__doc__ = "Blender Studio API"


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('', home_view, name='home'),
    path('welcome/', welcome_view, name='welcome'),
    path('comments/', include(comments.urls)),
    path('films/', film_list, name='film-list'),
    path('projects/', include(projects.urls)),
    path('training/', include(training.urls)),
    path('blog/', include(blog.urls)),
    path('api/markdown-preview', markdown_preview_view, name='api-markdown-preview'),
    path('api/', include((router.urls, 'api'), namespace='api')),
    path('', include(characters.urls)),
    path('search/', include(search.urls)),
    path('looper/', include((looper.urls), namespace='looper')),
    path('', include((subscriptions.urls), namespace='subscriptions')),
    path('', include(users.urls)),
    path('', include(static_assets.urls)),
    path('stats/', include('stats.urls')),
    path('activity/', include('actstream.urls')),
    re_path(r'^webhooks/', include('anymail.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('s3direct/', include('s3direct.urls')),
]

handler400 = error_views.ErrorView.as_view(template_name='common/errors/400.html', status=400)
handler403 = error_views.ErrorView.as_view(template_name='common/errors/403.html', status=403)
handler404 = error_views.ErrorView.as_view(template_name='common/errors/404.html', status=404)
handler500 = error_views.ErrorView.as_view(template_name='common/errors/500.html', status=500)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Test different error pages by changing the template (400.html, 403.html, etc.)
    urlpatterns += [path('error', TemplateView.as_view(template_name='common/errors/404.html'))]

    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

# Flatpages catch-all
urlpatterns += [
    re_path(r'^(?P<url>.*/)$', views.flatpage),
]

projects/models/assets.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.urls.base import reverse
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager

from comments.models import Comment
from common import mixins
from projects.models import Collection
import common.help_texts
import static_assets.models as models_static_assets

User = get_user_model()


class AssetCategory(models.TextChoices):
    artwork = 'artwork', 'Artwork'
    production_file = 'production_file', 'Production File'
    production_lesson = 'production_lesson', 'Production Lesson'


class Asset(mixins.CreatedUpdatedMixin, models.Model):
    """This represents the leaf of the tree of project-related resources.

    An asset can be of one of the three types: image, video, or file.
    """

    class Meta:
        ordering = ['-date_published', 'order']

    date_published = models.DateTimeField(default=timezone.now)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='assets')
    static_asset = models.ForeignKey(
        'static_assets.StaticAsset',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='assets',
    )

    collection = models.ForeignKey(
        Collection, blank=True, null=True, on_delete=models.SET_NULL, related_name='assets'
    )
    order = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=512)
    slug = models.SlugField(blank=True)
    description = models.TextField(blank=True, help_text=common.help_texts.markdown_with_html)
    category = models.CharField(choices=AssetCategory.choices, max_length=17, db_index=True)
    view_count = models.PositiveIntegerField(default=0, editable=False)
    is_published = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    is_free = models.BooleanField(default=False)
    is_spoiler = models.BooleanField(default=False)
    contains_blend_file = models.BooleanField(
        default=False, help_text='Is the asset a .blend file or a package containing .blend files?'
    )
    attachments = models.ManyToManyField(
        models_static_assets.StaticAsset, blank=True, related_name='+'
    )

    comments = models.ManyToManyField(Comment, through='AssetComment', related_name='asset')
    tags = TaggableManager(blank=True)

    def clean(self) -> None:
        # TODO(fsiddi) Add background job to update file metadata for static_asset on the bucket
        super().clean()
        if not self.slug:
            self.slug = slugify(self.name)[:50]
        if self.collection and self.collection.project != self.project:
            raise ValidationError('Collection\'s project does not match the asset\'s project.')

    def __str__(self) -> str:
        return (
            f'{self.project}: {self.name}'
            f'{self.is_free and " 🆓" or ""}{self.is_featured and " ★" or ""}'
        )

    @property
    def size_bytes(self) -> int:
        if not self.static_asset:
            return 0
        if self.static_asset.source_type == 'video':
            variation = self.static_asset.video.variations.first()
            if not variation:
                return self.static_asset.size_bytes
            return variation.size_bytes
        else:
            return self.static_asset.size_bytes

    def get_absolute_url(self) -> str:
        return self.url

    @property
    def url(self) -> str:
        """Returns link to asset in collection or in Featured Gallery.

        The primary place where assets are displayed is collections in project gallery.
        Some assets (e.g. projects) do not belong to collections, but are displayed as featured.
        If none of the above conditions applies, the asset is probably not available anywhere
        on the website, and the url property returns an empty string.
        """
        if self.is_featured:
            gallery_url = reverse('project-gallery', kwargs={'project_slug': self.project.slug})
            return f'{gallery_url}?asset={self.pk}'
        if self.collection:
            collection_url = reverse(
                'collection-detail',
                kwargs={'project_slug': self.project.slug, 'collection_slug': self.collection.slug},
            )
            return f'{collection_url}?asset={self.pk}'
        return ''

    @property
    def comment_url(self) -> str:
        return reverse('api-asset-comment', kwargs={'asset_pk': self.pk})

    @property
    def admin_url(self) -> str:
        return reverse('admin:projects_asset_change', args=[self.pk])

    @property
    def like_url(self) -> str:
        return reverse('api-asset-like', kwargs={'asset_pk': self.pk})


class AssetComment(models.Model):
    """This is an intermediary model between Asset and Comment.

    An AssetComment should in fact only relate to one Comment, hence the
    OneToOne comment field.
    """

    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    comment = models.OneToOneField(Comment, on_delete=models.CASCADE)


class Like(mixins.CreatedUpdatedMixin, models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'asset'], name='only_one_like_per_asset_and_user'
            )
        ]

    # Whenever a User is deleted their Like lives on to ensure integrity of the conversation.
    # Instead, we remove the reference to the User to honor the deletion request as much as
    # possible.
    user = models.ForeignKey(
        User, null=True, blank=False, on_delete=models.SET_NULL, related_name='liked_assets'
    )
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, related_name='likes')

    def __str__(self) -> str:
        return f'Like by {self.username} on {self.asset}'

    @property
    def username(self) -> str:
        return '<deleted>' if self.user is None else self.user.username

projects/models/projects.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model

from common import mixins
from common.upload_paths import get_upload_to_hashed_path

User = get_user_model()


class ProjectStatus(models.TextChoices):
    in_development = '0_dev', 'In Development'
    in_production = '1_prod', 'In Production'
    released = '2_released', 'Released'


class Project(mixins.CreatedUpdatedMixin, mixins.StaticThumbnailURLMixin, models.Model):
    class ProjectCategory(models.TextChoices):
        FILM = 'film', 'Film'
        SHOWCASE = 'showcase', 'Showcase'
        OTHER = 'other', 'Other'

    title = models.CharField(unique=True, max_length=512)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField()
    description.description = 'Description consisting of a few sentences.'
    summary = models.TextField()
    summary.description = 'Summary consisting of multiple paragraphs.'

    category = models.CharField(
        max_length=128,
        choices=ProjectCategory.choices,
        default=ProjectCategory.FILM,
    )

    status = models.TextField(choices=ProjectStatus.choices)
    release_date = models.DateField(blank=True, null=True)
    release_date.description = "Past or planned release date of the project."
    is_published = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)

    logo = models.FileField(
        blank=True,
        null=True,
        upload_to=get_upload_to_hashed_path,
        help_text='A PNG picture with transparency, featuring the logo.',
    )
    poster = models.FileField(
        blank=True,
        null=True,
        upload_to=get_upload_to_hashed_path,
        help_text='A 1508x2133 poster for the project.',
    )
    picture_header = models.FileField(
        blank=True,
        null=True,
        upload_to=get_upload_to_hashed_path,
        help_text='A 1920x850 header image. No text.',
    )
    thumbnail = models.FileField(
        upload_to=get_upload_to_hashed_path, help_text='A 1920x1080 image for social media preview.'
    )
    youtube_link = models.URLField(blank=True)
    crew = models.ManyToManyField(User, through='projects.ProjectCrew')

    show_content_gallery_nav_link = models.BooleanField(
        default=True,
        help_text='Display a link to content gallery in the navigation.',
    )
    show_production_logs_nav_link = models.BooleanField(
        default=False,
        help_text='Display a link to production logs in the navigation.',
    )
    show_production_logs_as_featured = models.BooleanField(
        default=False,
        help_text='Display production logs instead of the featured gallery on the project page.',
    )
    show_blog_posts = models.BooleanField(
        default=False,
        help_text='Display latest blog posts on the project page.',
    )
    show_landing_page = models.BooleanField(
        default=False, help_text='Show a landing page to non-subscribers instead of project content'
    )

    class Meta:
        # Sort by release date descending,
        # fall back to created date in case the project hasn't been released yet.
        ordering = ('-release_date', '-date_created')

    def clean(self) -> None:
        super().clean()
        if not self.slug:
            self.slug = slugify(self.title)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self) -> str:
        return self.url

    @property
    def url(self) -> str:
        return reverse('project-detail', kwargs={'project_slug': self.slug})

    @property
    def admin_url(self) -> str:
        return reverse('admin:projects_project_change', args=[self.pk])


class ProjectCrew(models.Model):
    """People that are involved in the film production.

    Used to set their role (Director, Animator, Art Director, etc) and
    display it in the production logs.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='project_crew')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    role = models.CharField(max_length=128)

    class Meta:
        unique_together = ['user', 'project']

    def __str__(self) -> str:
        return f"{self.user.username} - {self.role}"


class FilmProductionCredit(mixins.CreatedUpdatedMixin, models.Model):
    """Production Credit for subscribers.

    Credits are granted based on the amount of time a user kept their subscription
    active. Credits are opt-in. This means that by default a credit will not
    be displayed on the site and it will be ignored by the 'generate_production_credits_scroll'
    script.
    """

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='production_credits')
    # Populated after running a one-time script, when locking the credit list
    display_name = models.CharField(max_length=128, blank=True, null=True)
    is_public = models.BooleanField(
        default=None,
        null=True,
        help_text='Display your name in the project credits.',
    )
    # Made not-editable after running a one-time script
    is_editable = models.BooleanField(default=True)

    class Meta:
        unique_together = ['user', 'project']

    def __str__(self) -> str:
        return f"{self.user.username} - {self.project}"

projects/templates/projects/components/breadcrumbs.html
{% load common_extras %}
{% load project_extras %}

<nav class="row mb-3 position-relative z-2" aria-label="breadcrumb">

  <ol class="breadcrumb col mb-n1">
    {% for name, url in breadcrumbs %}
      <li class="breadcrumb-item">
        <a class="btn btn-link mb-1" href="{{ url }}">
          {{ name }}
        </a>
      </li>
    {% endfor %}
    <li class="active breadcrumb-item">
      <span class="btn btn-link disabled mb-1">
        {{ current_location }}
      </span>
    </li>
  </ol>

  <div class="button-toolbar col-auto flex-grow-0 flex-shrink-1 mt-0">
    {% if user_can_edit_collection %}
      {% url 'admin:projects_asset_changelist' as list_url %}
      {% url 'admin:projects_newasset_add' as add_url %}
      {% url 'admin:projects_collection_add' as add_collection_url %}
      <a href="{{ add_url }}?project={{ project.id }}&is_published=1{% if current_collection.admin_url %}&collection={{ current_collection.id }}{% elif featured_artwork %}&is_featured=1{% endif %}" class="btn btn-admin" title="Add a new asset to {% firstof current_collection "featured" %}" data-bs-toggle="tooltip" data-placement="top">
        <i class="i-plus"></i>
      </a>
      <a href="{% if current_collection.admin_url %}{{ current_collection.admin_url }}{% elif featured_artwork %}{{ list_url }}?project__id__exact={{ project.id }}&is_featured__exact=1{% endif %}" class="btn btn-admin" title="Edit {% firstof current_collection "featured assets" %}"
        data-bs-toggle="tooltip" data-placement="top">
        <i class="i-edit"></i>
      </a>
      <a href="{{ add_collection_url }}?next-view-link=1&project={{ project.id }}{% if current_collection.admin_url %}&parent={{ current_collection.id }}{% endif %}" class="btn btn-admin" title="Create a new collection{% if current_collection %} in {{current_collection}}{% endif %}" data-bs-toggle="tooltip" data-placement="top">
        <i class="i-folder-plus"></i>
      </a>
      {# If collection is empty, display a Delete button #}
      {% if perms.projects.delete_collection and current_collection.assets.count == 0 and current_collection.child_collections.count == 0 %}
        {% url 'admin:projects_collection_delete' object_id=current_collection.id as delete_collection_url %}
        {% url 'project-gallery' project_slug=project.slug as gallery_url %}
        <a href="{{ delete_collection_url }}?next={% firstof current_collection.parent.url gallery_url %}" class="btn btn-admin" title="Delete this empty collection">
          <i class="i-trash"></i>
          Delete
        </a>
      {% endif %}
    {% endif %}

    <button data-bs-toggle="dropdown" class="btn btn-link">
      <i class="i-more-vertical"></i>
    </button>
    <div class="dropdown-menu dropdown-menu-end">
      <a href="https://projects.blender.org/studio/blender-studio/issues/new" target="_blank" class="dropdown-item">
        <i class="i-flag"></i>
        <span>Report Problem</span>
      </a>
    </div>
  </div>
</nav>

projects/templates/projects/components/card_film.html
<div class="cards-item-film cards-item">
  <a aria-label="{{ post.title }}" class="cards-item-content" href="{{ project.url }}">
    <div class="cards-item-thumbnail">
      {% include "common/components/helpers/image_resize.html" with alt=project.title img_source=project.poster width="500" %}
    </div>
    <h3 class="cards-item-title">
      <span class="me-2">{{ project.title }}</span>
      {% if project.status == "1_prod" %}
        <span class="badge badge-primary">
          {{ project.get_status_display }}
        </span>
      {% elif project.status == "2_released" %}
        <span class="badge">
          {{ project.release_date|date:"Y" }}
        </span>
      {% else %}
        <span class="badge">
          {{ project.get_status_display }}
        </span>
      {% endif %}
    </h3>
    <div class="cards-item-excerpt">
      <p>
        {{ project.description }}
      </p>
    </div>
  </a>
</div>

projects/templates/projects/components/card_project.html
<div class="cards-item card-project">
  <a aria-label="{{ post.title }}" class="cards-item-content" href="{{ project.url }}">
    <div class="cards-item-thumbnail">
      {% include "common/components/helpers/image_resize.html" with alt=project.title img_source=project.thumbnail width="500" %}
    </div>

    {% if project.category %}
    <div class="cards-item-headline">{{ project.get_category_display }}</div>
    {% endif %}

    <h3 class="cards-item-title">
      {{ project.title }}
    </h3>

    {% if project.description %}
    <div class="cards-item-excerpt text-secondary">
      <p>
        {{ project.description }}
      </p>
    </div>
    {% endif %}

    {% if project.status or project.is_featured or not project.is_published %}
    <div class="cards-item-extra">
      <ul class="list-inline w-100">
        {% if project.is_featured %}
        <li>
          <span class="badge badge-success px-2">
            <i class="i-star"></i> Featured
          </span>
        </li>
        {% endif %}

        {% if project.status %}
        <li>
          <span class="badge badge-primary"><i class="i-activity"></i> {{ project.get_status_display }}</span>
        </li>
        {% endif %}

        {% if not project.is_published %}
        <li>
          {% include "common/components/cards/pill.html" with label='Unpublished' class="badge-danger" %}
        </li>
        {% endif %}
    </div>
    {% endif %}
  </a>
</div>

projects/templates/projects/components/jumbotron_project.html
<div class="hero hero-film">
  <div class="container">
    <div class="hero-content">
      {% if project.logo %}
      <img class="film-logo" src="{{ project.logo.url }}" alt="{{ project.title }} Logo">
      {% else %}
      <h1>{{ project.title }}</h1>
      {% endif %}
      <p class="hero-subtitle">
        {{ project.summary|linebreaksbr }}
      </p>
      <div class="hero-cta-container">
        <div class="btn-row">
          {% if project.youtube_link != "" %}
            {# Class 'video-modal-link' is needed for js #}
            <button class="btn btn-accent video-modal-link" data-bs-toggle="modal" data-bs-target="#videoModal" data-video="{{ project.youtube_link }}">
              <i class="i-youtube"></i>
              <span>Watch {{ project.title }}</span>
            </button>
            {% if project.show_content_gallery_nav_link %}
            <a class="btn btn-link" href="{% url 'project-gallery' project.slug %}">Explore Content Gallery</a>
            {% endif %}
          {% else %}
            {% if project.show_content_gallery_nav_link %}
            <a class="btn btn-accent" href="{% url 'project-gallery' project.slug %}">Explore Content Gallery</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% if project.picture_header %}
  <div class="hero-bg" style="background-image: url('{{ project.picture_header.url }}'); background-position-y: 50%"></div>
  {% endif %}
  <div class="hero-overlay-gradient"></div>
</div>

projects/templates/projects/components/pagination_dates.html
<nav aria-label="page navigation">
  {% with current=object_list|first %}
    {% with current_month=current.start_date|date:"YM"|lower %}
      <ul class="pagination pe-md-0">
        {% if next_month %}
          <li class="page-item">
            <a href="{% url 'production-logs-month' project_slug=project.slug year=next_month.year month=next_month|date:"M"|lower %}"><i class="i-chevron-left"></i></a>
          </li>

          {% if next_month != date_list|first %}
            <li class="page-item">
              <a href="{% url 'production-logs-month' project_slug=project.slug year=date_list|first|date:"Y"|lower month=date_list|first|date:"M"|lower %}">{{ date_list|first|date:"M y" }}</a>
            </li>
            <li class="page-item disabled">
              ...
            </li>
          {% endif %}
        {% endif %}

        {% for date in date_list %}
          {% with month=date|date:"YM"|lower %}
            {% if current_month == month or date == previous_month or date == next_month %}
              <li class="page-item {% if current_month == month %}active{% endif %} ">
                <a href="{% url 'production-logs-month' project_slug=project.slug year=date.year month=date|date:"M"|lower %}">{{ date|date:"M y" }}</a>
              </li>
            {% endif %}
          {% endwith %}
        {% endfor %}

        {% if previous_month %}
          {% if previous_month != date_list|last %}
            <li class="page-item disabled">
              ...
            </li>
            <li class="page-item">
              <a href="{% url 'production-logs-month' project_slug=project.slug year=date_list|last|date:"Y"|lower month=date_list|last|date:"M"|lower %}">{{ date_list|last|date:"M y" }}</a>
            </li>
          {% endif %}
          <li class="page-item">
            <a href="{% url 'production-logs-month' project_slug=project.slug year=previous_month.year month=previous_month|date:"M"|lower %}"><i class="i-chevron-right"></i></a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
  {% endwith %}
</nav>

projects/templates/projects/components/production_log_pagination.html
<div class="row justify-content-end mt-3">
  <div class="col-auto text-center">
    <nav aria-label="ProductionLog page navigation">
      <ul class="pagination mb-0">
        {% if next %}
          <li class="page-item">
            <a href="{% url 'production-log' project_slug=project.slug pk=next.pk %}"><i class="i-chevron-left"></i></a>
          </li>
        {% endif %}
        <li class="page-item active">
          <a href="#">{{ production_log.name }}</a>
        </li>
        {% if previous %}
          <li class="page-item">
            <a href="{% url 'production-log' project_slug=project.slug pk=previous.pk %}"><i class="i-chevron-right"></i></a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>